#########
# Setup #
#########

substitutions:
  ap: "Detector"
  name: detector

esphome:
  name: $name

esp32:
  board: esp32dev
  framework:
    type: arduino

############
# Packages #
############

packages:
  # Connection
  connection: !include common/connection.yaml
  # Extras
  extras: !include common/extras.yaml
  estras-32: !include common/extras-32.yaml

###########
# Display #
###########

spi:
  clk_pin: GPIO18   # E
  mosi_pin: GPIO19  # RW
  interface: spi2

font:
  - file: "assets/courier.ttf"
    id: courier
    size: 12

display:
  - platform: st7920
    rotation: 270
    update_interval: 10s
    cs_pin:
      number: GPIO22  # RS
      inverted: true
    width: 128
    height: 64
    lambda: |-
      it.print(0, 10, id(courier), "Hello!");

# Backlight
switch:
  - platform: gpio
    pin: GPIO23
    name: "Backlight"
    icon: "mdi:brightness-5"
    id: backlight
    on_turn_on:
    - delay: 4s
    - switch.turn_off: backlight

##########
# Button #
##########

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
    on_click:
      then:
        - switch.turn_on: backlight
