#########
# Setup #
#########

substitutions:
  friendly: "Dimmer"
  name: dimmer-candeo
  # Timings
  transition: 100ms

esphome:
  name: $name
  friendly_name: $friendly
  name_add_mac_suffix: true

esp8266:
  board: esp8285

############
# Packages #
############

packages:
  # Connection
  connection: !include common/connection.yaml

##########
# Extras #
##########

logger:
  baud_rate: 0

sensor:
  - platform: uptime
    name: Uptime

switch:
  - platform: restart
    name: Restart

############
# Tuya MCU #
############

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

tuya:
  ignore_mcu_update_on_datapoints:
    - 5
    - 3

##########
# Dimmer #
##########

light:
  - platform: "tuya"
    name: "Dimmer"
    restore_mode: RESTORE_DEFAULT_OFF
    # default_transition_length: $transition
    switch_datapoint: 1
    dimmer_datapoint: 2
    min_value: 10
    max_value: 1000
