#########
# Setup #
#########

esphome:
  friendly_name: Light
  name: light
  name_add_mac_suffix: true

esp8266:
  board: esp8285

############
# Packages #
############

packages:
  # Connection
  connection: !include common/connection.yaml
  # Extras
  extras: !include common/extras.yaml

###############
# Connections #
###############

web_server:
  port: 80

###########
# Outputs #
###########

output:

  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true

  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true

  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true

  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5
    min_power: 0.01
    max_power: 0.9
    zero_means_zero: true

  - platform: esp8266_pwm
    id: ct_output
    inverted: true
    pin: GPIO13
    min_power: 0.01
    max_power: 0.9
    zero_means_zero: true

light:

  - platform: rgbct
    id: rgbct_light
    name: "RGBCCT_Bulb"
    restore_mode: RESTORE_DEFAULT_OFF
    red: red_output
    green: green_output
    blue: blue_output
    white_brightness: white_output
    color_temperature: ct_output
    cold_white_color_temperature: 6000K
    warm_white_color_temperature: 3000K
    color_interlock: true
