#########
# Setup #
#########

esphome:
  name: remote-box-down

esp32:
  board: esp32dev
  framework:
    type: arduino

#############
# Receivers #
#############

remote_receiver:
  - id: receiver_ir
    pin:
      number: GPIO23
      inverted: true
    dump: all

  - id: receiver_rf
    pin: GPIO25
    dump: all
    # Settings to optimize recognition of RF devices
    tolerance: 50%
    filter: 250us
    idle: 4ms

remote_transmitter:
  - id: transmitter_ir
    pin: GPIO2
    # Infrared remotes use a 50% carrier signal
    carrier_duty_percent: 50%

  - id: transmitter_rf
    pin: GPIO22
    # RF uses a 100% carrier signal
    carrier_duty_percent: 100%

###########
# Actions #
###########

script:

# ### Soundbar ### #

  - id: soundbar_power
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8001

  - id: soundbar_input
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8002

  - id: soundbar_mute
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8033

  - id: soundbar_volume_up
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8003

  - id: soundbar_volume_down
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8008

  - id: soundbar_bass_up
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8004

  - id: soundbar_bass_down
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8026

  - id: soundbar_trebble_up
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8025

  - id: soundbar_trebble_down
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8027

# ### HDMI Switch ### #

  - id: hdmi_switch_power_on
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x805C

  - id: hdmi_switch_power_off
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801F

  - id: hdmi_switch_device_1
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801B

  - id: hdmi_switch_device_2
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801E

  - id: hdmi_switch_device_3
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800D

  - id: hdmi_switch_device_4
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8012

  - id: hdmi_switch_device_5
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8010

  - id: hdmi_switch_device_up
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800C

  - id: hdmi_switch_device_down
    then:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8005

# ### Roku ### #

  - id: roku_home
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743C13E
          nbits: 32

  - id: roku_back
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57436798
          nbits: 32

  - id: roku_up
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57439966
          nbits: 32

  - id: roku_left
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57437986
          nbits: 32

  - id: roku_down
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743CD32
          nbits: 32

  - id: roku_right
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743B54A
          nbits: 32

  - id: roku_select
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x07035FA0
          nbits: 32

  - id: roku_replay
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57431FE0
          nbits: 32

  - id: roku_options
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57438778
          nbits: 32

  - id: roku_previous
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57432DD2
          nbits: 32

  - id: roku_next
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743AB54
          nbits: 32

  - id: roku_play_pause
    then:
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x574333CC
          nbits: 32

############
# Soundbar #
############

button:

  - platform: template
    name: Soundbar Power
    icon: "mdi:power"
    on_press:
      - script.execute: soundbar_power

  - platform: template
    name: Soundbar Input
    icon: "mdi:video-input-hdmi"
    on_press:
      - script.execute: soundbar_input

  - platform: template
    name: Soundbar Mute
    icon: "mdi:volume-mute"
    on_press:
      - script.execute: soundbar_mute

  - platform: template
    name: Soundbar Volume Up
    icon: "mdi:volume-plus"
    on_press:
      - script.execute: soundbar_volume_up

  - platform: template
    name: Soundbar Volume Down
    icon: "mdi:volume-minus"
    on_press:
      - script.execute: soundbar_volume_down

  - platform: template
    name: Soundbar Bass Up
    icon: "mdi:chevron-up-box"
    on_press:
      - script.execute: soundbar_bass_up

  - platform: template
    name: Soundbar Bass Down
    icon: "mdi:chevron-down-box"
    on_press:
      - script.execute: soundbar_bass_down

  - platform: template
    name: Soundbar Trebble Up
    icon: "mdi:chevron-up-box-outline"
    on_press:
      - script.execute: soundbar_trebble_up

  - platform: template
    name: Soundbar Trebble Down
    icon: "mdi:chevron-down-box-outline"
    on_press:
      - script.execute: soundbar_trebble_down

###############
# HDMI Switch #
###############

  - platform: template
    name: HDMI Switch Power On
    icon: "mdi:power-on"
    on_press:
      - script.execute: hdmi_switch_power_on

  - platform: template
    name: HDMI Switch Power Off
    icon: "mdi:power-off"
    on_press:
      - script.execute: hdmi_switch_power_off

  - platform: template
    name: HDMI Switch Device_1
    icon: "mdi:numeric-1"
    on_press:
      - script.execute: hdmi_switch_device_1

  - platform: template
    name: HDMI Switch Device_2
    icon: "mdi:numeric-2"
    on_press:
      - script.execute: hdmi_switch_device_2

  - platform: template
    name: HDMI Switch Device_3
    icon: "mdi:numeric-3"
    on_press:
      - script.execute: hdmi_switch_device_3

  - platform: template
    name: HDMI Switch Device_4
    icon: "mdi:numeric-4"
    on_press:
      - script.execute: hdmi_switch_device_4

  - platform: template
    name: HDMI Switch Device_5
    icon: "mdi:numeric-5"
    on_press:
      - script.execute: hdmi_switch_device_5

  - platform: template
    name: HDMI Switch Device Up
    icon: "mdi:arrow-up-box"
    on_press:
      - script.execute: hdmi_switch_device_up

  - platform: template
    name: HDMI Switch Device Down
    icon: "mdi:arrow-down-box"
    on_press:
      - script.execute: hdmi_switch_device_down

###########
# Roku IR #
###########

  - platform: template
    name: Roku Home
    icon: "mdi:home"
    on_press:
      - script.execute: roku_home

  - platform: template
    name: Roku Back
    icon: "mdi:keyboard-backspace"
    on_press:
      - script.execute: roku_back

  - platform: template
    name: Roku Up
    icon: "mdi:arrow-up-box"
    on_press:
      - script.execute: roku_up

  - platform: template
    name: Roku Left
    icon: "mdi:arrow-left-box"
    on_press:
      - script.execute: roku_left

  - platform: template
    name: Roku Down
    icon: "mdi:arrow-down-box"
    on_press:
      - script.execute: roku_down

  - platform: template
    name: Roku Right
    icon: "mdi:arrow-right-box"
    on_press:
      - script.execute: roku_right

  - platform: template
    name: Roku Select
    icon: "mdi:cursor-default-click"
    on_press:
      - script.execute: roku_select

  - platform: template
    name: Roku Replay
    icon: "mdi:replay"
    on_press:
      - script.execute: roku_replay

  - platform: template
    name: Roku Options
    icon: "mdi:dots-horizontal-circle"
    on_press:
      - script.execute: roku_options

  - platform: template
    name: Roku Previous
    icon: "mdi:rewind"
    on_press:
      - script.execute: roku_previous

  - platform: template
    name: Roku Next
    icon: "mdi:fast-forward"
    on_press:
      - script.execute: roku_next

  - platform: template
    name: Roku Play Pause
    icon: "mdi:play-pause"
    on_press:
      - script.execute: roku_play_pause

##############
# Connection #
##############

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret device_password

ota:
  - platform: esphome
    password: !secret device_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Remote Box Down"
    password: !secret ap_password

captive_portal:

