#########
# Setup #
#########

esphome:
  name: remote-box-down

esp32:
  board: esp32dev
  framework:
    type: arduino

#############
# Receivers #
#############

remote_receiver:
  - id: receiver_ir
    pin:
      number: GPIO23
      inverted: true
    dump: all

  - id: receiver_rf
    pin: GPIO25
    dump: all
    # Settings to optimize recognition of RF devices
    tolerance: 50%
    filter: 250us
    idle: 4ms

remote_transmitter:
  - id: transmitter_ir
    pin: GPIO2
    # Infrared remotes use a 50% carrier signal
    carrier_duty_percent: 50%

  - id: transmitter_rf
    pin: GPIO22
    # RF uses a 100% carrier signal
    carrier_duty_percent: 100%

############
# Soundbar #
############

button:

  - platform: template
    name: Soundbar Power
    icon: "mdi:power"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8001

  - platform: template
    name: Soundbar Input
    icon: "mdi:video-input-hdmi"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8002

  - platform: template
    name: Soundbar Mute
    icon: "mdi:volume-mute"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8033

  - platform: template
    name: Soundbar Volume Up
    icon: "mdi:volume-plus"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8003

  - platform: template
    name: Soundbar Volume Down
    icon: "mdi:volume-minus"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8008

  - platform: template
    name: Soundbar Bass Up
    icon: "mdi:chevron-up-box"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8004

  - platform: template
    name: Soundbar Bass Down
    icon: "mdi:chevron-down-box"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8026

  - platform: template
    name: Soundbar Trebble Up
    icon: "mdi:chevron-up-box-outline"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8025

  - platform: template
    name: Soundbar Trebble Down
    icon: "mdi:chevron-down-box-outline"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8027

###############
# HDMI Switch #
###############

  - platform: template
    name: HDMI Switch Power On
    icon: "mdi:power-on"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x805C

  - platform: template
    name: HDMI Switch Power Off
    icon: "mdi:power-off"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801F

  - platform: template
    name: HDMI Switch Device 1
    icon: "mdi:numeric-1"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801B

  - platform: template
    name: HDMI Switch Device 2
    icon: "mdi:numeric-2"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801E

  - platform: template
    name: HDMI Switch Device 3
    icon: "mdi:numeric-3"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800D

  - platform: template
    name: HDMI Switch Device 4
    icon: "mdi:numeric-4"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8012

  - platform: template
    name: HDMI Switch Device 5
    icon: "mdi:numeric-5"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8010

  - platform: template
    name: HDMI Switch Device Up
    icon: "mdi:arrow-up-box"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800C

  - platform: template
    name: HDMI Switch Device Down
    icon: "mdi:arrow-down-box"
    on_press:
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8005

##############
# Connection #
##############

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret device_password

ota:
  - platform: esphome
    password: !secret device_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Remote Box Down"
    password: !secret ap_password

captive_portal:

