#########
# Setup #
#########

substitutions:
  ap: "Remote Box Down"
  name: remote-box-down

esphome:
  name: $name

esp32:
  board: esp32dev
  framework:
    type: arduino

############
# Packages #
############

packages:
  # Connection
  connection: !include common/connection.yaml
  # Extras
  extras: !include common/extras.yaml
  estras-32: !include common/extras-32.yaml
  # Codes
  codes: !include remote/codes.yaml

#############
# Receivers #
#############

remote_receiver:
  - id: receiver_ir
    pin:
      number: GPIO23
      inverted: true
    # dump: all

  - id: receiver_rf
    pin: GPIO25
    dump: all
    # Settings to optimize recognition of RF devices
    tolerance: 50%
    filter: 250us
    idle: 4ms

remote_transmitter:
  - id: transmitter_ir
    pin: GPIO2
    # Infrared remotes use a 50% carrier signal
    carrier_duty_percent: 50%

  - id: transmitter_rf
    pin: GPIO22
    # RF uses a 100% carrier signal
    carrier_duty_percent: 100%

############
# Soundbar #
############

button:

  - platform: template
    name: Soundbar Power
    icon: "mdi:power"
    on_press:
      - script.execute: soundbar_power

  - platform: template
    name: Soundbar Input
    icon: "mdi:video-input-hdmi"
    on_press:
      - script.execute: soundbar_input

  - platform: template
    name: Soundbar Mute
    icon: "mdi:volume-mute"
    on_press:
      - script.execute: soundbar_mute

  - platform: template
    name: Soundbar Volume Up
    icon: "mdi:volume-plus"
    on_press:
      - script.execute: soundbar_volume_up

  - platform: template
    name: Soundbar Volume Down
    icon: "mdi:volume-minus"
    on_press:
      - script.execute: soundbar_volume_down

  - platform: template
    name: Soundbar Bass Up
    icon: "mdi:chevron-up-box"
    on_press:
      - script.execute: soundbar_bass_up

  - platform: template
    name: Soundbar Bass Down
    icon: "mdi:chevron-down-box"
    on_press:
      - script.execute: soundbar_bass_down

  - platform: template
    name: Soundbar Trebble Up
    icon: "mdi:chevron-up-box-outline"
    on_press:
      - script.execute: soundbar_trebble_up

  - platform: template
    name: Soundbar Trebble Down
    icon: "mdi:chevron-down-box-outline"
    on_press:
      - script.execute: soundbar_trebble_down

###############
# HDMI Switch #
###############

  - platform: template
    name: HDMI Switch Power On
    icon: "mdi:power-on"
    on_press:
      - script.execute: hdmi_switch_power_on

  - platform: template
    name: HDMI Switch Power Off
    icon: "mdi:power-off"
    on_press:
      - script.execute: hdmi_switch_power_off

  - platform: template
    name: HDMI Switch Device 1
    icon: "mdi:numeric-1"
    on_press:
      - script.execute: hdmi_switch_device_1

  - platform: template
    name: HDMI Switch Device 2
    icon: "mdi:numeric-2"
    on_press:
      - script.execute: hdmi_switch_device_2

  - platform: template
    name: HDMI Switch Device 3
    icon: "mdi:numeric-3"
    on_press:
      - script.execute: hdmi_switch_device_3

  - platform: template
    name: HDMI Switch Device 4
    icon: "mdi:numeric-4"
    on_press:
      - script.execute: hdmi_switch_device_4

  - platform: template
    name: HDMI Switch Device 5
    icon: "mdi:numeric-5"
    on_press:
      - script.execute: hdmi_switch_device_5

  - platform: template
    name: HDMI Switch Device Up
    icon: "mdi:arrow-up-box"
    on_press:
      - script.execute: hdmi_switch_device_up

  - platform: template
    name: HDMI Switch Device Down
    icon: "mdi:arrow-down-box"
    on_press:
      - script.execute: hdmi_switch_device_down

###########
# Roku IR #
###########

  - platform: template
    name: Roku Home
    icon: "mdi:home"
    on_press:
      - script.execute: roku_home

  - platform: template
    name: Roku Back
    icon: "mdi:keyboard-backspace"
    on_press:
      - script.execute: roku_back

  - platform: template
    name: Roku Up
    icon: "mdi:menu-up"
    on_press:
      - script.execute: roku_up

  - platform: template
    name: Roku Left
    icon: "mdi:menu-left"
    on_press:
      - script.execute: roku_left

  - platform: template
    name: Roku Down
    icon: "mdi:menu-down"
    on_press:
      - script.execute: roku_down

  - platform: template
    name: Roku Right
    icon: "mdi:menu-right"
    on_press:
      - script.execute: roku_right

  - platform: template
    name: Roku Select
    icon: "mdi:cursor-default-click"
    on_press:
      - script.execute: roku_select

  - platform: template
    name: Roku Replay
    icon: "mdi:replay"
    on_press:
      - script.execute: roku_replay

  - platform: template
    name: Roku Options
    icon: "mdi:dots-horizontal-circle"
    on_press:
      - script.execute: roku_options

  - platform: template
    name: Roku Previous
    icon: "mdi:rewind"
    on_press:
      - script.execute: roku_previous

  - platform: template
    name: Roku Next
    icon: "mdi:fast-forward"
    on_press:
      - script.execute: roku_next

  - platform: template
    name: Roku Play Pause
    icon: "mdi:play-pause"
    on_press:
      - script.execute: roku_play_pause

##############
# Samsung TV #
##############

  - platform: template
    name: Samsung Power
    icon: "mdi:power"
    on_press:
      - script.execute: samsung_power

  - platform: template
    name: Samsung Source
    icon: "mdi:video-input-hdmi"
    on_press:
      - script.execute: samsung_source

  - platform: template
    name: Samsung Mute
    icon: "mdi:volume-mute"
    on_press:
      - script.execute: samsung_mute

  - platform: template
    name: Samsung Volume Up
    icon: "mdi:volume-plus"
    on_press:
      - script.execute: samsung_volume_up

  - platform: template
    name: Samsung Volume Down
    icon: "mdi:volume-minus"
    on_press:
      - script.execute: samsung_volume_down

  - platform: template
    name: Samsung Channel List
    icon: "mdi:list-box"
    on_press:
      - script.execute: samsung_channel_list

  - platform: template
    name: Samsung Channel Up
    icon: "mdi:chevron-up-box"
    on_press:
      - script.execute: samsung_channel_up

  - platform: template
    name: Samsung Channel Down
    icon: "mdi:chevron-down-box"
    on_press:
      - script.execute: samsung_channel_down

  - platform: template
    name: Samsung Home
    icon: "mdi:home"
    on_press:
      - script.execute: samsung_home

  - platform: template
    name: Samsung Up
    icon: "mdi:menu-up"
    on_press:
      - script.execute: samsung_up

  - platform: template
    name: Samsung Left
    icon: "mdi:menu-left"
    on_press:
      - script.execute: samsung_left

  - platform: template
    name: Samsung Down
    icon: "mdi:menu-down"
    on_press:
      - script.execute: samsung_down

  - platform: template
    name: Samsung Right
    icon: "mdi:menu-right"
    on_press:
      - script.execute: samsung_right

  - platform: template
    name: Samsung Select
    icon: "mdi:cursor-default-click"
    on_press:
      - script.execute: samsung_select

  - platform: template
    name: Samsung Return
    icon: "mdi:keyboard-backspace"
    on_press:
      - script.execute: samsung_return

  - platform: template
    name: Samsung Exit
    icon: "mdi:exit-to-app"
    on_press:
      - script.execute: samsung_exit

  - platform: template
    name: Samsung Settings
    icon: "mdi:cog"
    on_press:
      - script.execute: samsung_settings

############
# Receiver #
############

# ### URC1699 Haier (Power + Refresh) ### #

# Example configuration entry
binary_sensor:

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Power
    pioneer:
      rc_code_1: 0x2008
    on_press:
      then:
        - script.execute: samsung_power
        - script.execute: soundbar_power

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Source
    pioneer:
      rc_code_1: 0x200B
    on_press:
      - script.execute: samsung_source

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Channel List
    pioneer:
      rc_code_1: 0x204B

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Refresh
    pioneer:
      rc_code_1: 0x201A
    on_press:
      - script.execute: hdmi_switch_device_up

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Menu
    pioneer:
      rc_code_1: 0x2043

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Info
    pioneer:
      rc_code_1: 0x20AA

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Text
    pioneer:
      rc_code_1: 0x2057

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Home
    pioneer:
      rc_code_1: 0x2092
    on_press:
      - script.execute: roku_home

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Guide
    pioneer:
      rc_code_1: 0x20A9

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Up
    pioneer:
      rc_code_1: 0x2040
    on_press:
      - script.execute: roku_up

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Left
    pioneer:
      rc_code_1: 0x2007
    on_press:
      - script.execute: roku_left

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Down
    pioneer:
      rc_code_1: 0x2041
    on_press:
      - script.execute: roku_down

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Right
    pioneer:
      rc_code_1: 0x2006
    on_click:
      - script.execute: roku_left

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Select
    pioneer:
      rc_code_1: 0x2044
    on_press:
      - script.execute: roku_select

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Back
    pioneer:
      rc_code_1: 0x2047
    on_press:
      - script.execute: roku_back

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Exit
    pioneer:
      rc_code_1: 0x205B

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Mute
    pioneer:
      rc_code_1: 0x2009
    on_press:
      - script.execute: soundbar_mute

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Volume Up
    pioneer:
      rc_code_1: 0x2002
    on_press:
      - script.execute: soundbar_volume_up

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Volume Down
    pioneer:
      rc_code_1: 0x2003
    on_press:
      - script.execute: soundbar_volume_down

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Channel Up
    pioneer:
      rc_code_1: 0x2000

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Channel Down
    pioneer:
      rc_code_1: 0x2001

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Previous
    pioneer:
      rc_code_1: 0x20D3
    on_press:
      - script.execute: roku_previous

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Next
    pioneer:
      rc_code_1: 0x20D4
    on_press:
      - script.execute: roku_next

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Play
    pioneer:
      rc_code_1: 0x20B0
    on_press:
      - script.execute: roku_play_pause

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: URC Pause
    pioneer:
      rc_code_1: 0x20D6
    on_press:
      - script.execute: roku_play_pause
