#########
# Setup #
#########

substitutions:
  friendly: "Remote Box Up"
  name: remote-box-up

esphome:
  name: $name
  friendly_name: $friendly

############
# Packages #
############

packages:
  # Hardware
  hardware: !include common/remote.yaml
  # Connection
  connection: !include common/connection.yaml
  # Extras
  extras: !include common/extras.yaml
  extras-32: !include common/extras-32.yaml
  # Codes
  codes: !include remote/codes.yaml

button:

##########
# Screen #
##########

  - platform: template
    name: Screen Show
    icon: "mdi:projector-screen-variant-outline"
    on_press:
      - script.execute: screen_show

  - platform: template
    name: Screen Stop
    icon: "mdi:pause-octagon-outline"
    on_press:
      - script.execute: screen_stop

  - platform: template
    name: Screen Hide
    icon: "mdi:projector-screen-variant-off-outline"
    on_press:
      - script.execute: screen_hide

##############
# Converters #
##############

binary_sensor:

# ### Lights ### #

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Dimmer On
    pioneer:
      rc_code_1: 0x000D

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Dimmer Bright
    pioneer:
      rc_code_1: 0x0009

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Dimmer Dim
    pioneer:
      rc_code_1: 0x001D

# ### Screen ### #

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Screen Show
    internal: true
    pioneer:
      rc_code_1: 0x000A
    on_press:
      - script.execute: screen_show

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Screen Stop
    internal: true
    pioneer:
      rc_code_1: 0x0004
    on_press:
      - script.execute: screen_stop

  - platform: remote_receiver
    receiver_id: receiver_ir
    name: Screen Hide
    internal: true
    pioneer:
      rc_code_1: 0x0008
    on_press:
      - script.execute: screen_hide

