#########
# Setup #
#########

substitutions:
  friendly: "Socket"
  name: socket
  # ! Limits !
  current_limit: "10"
  temperature_limit: "65"

esphome:
  name: $name
  friendly_name: $friendly
  name_add_mac_suffix: true

bk72xx:
  board: cbu

############
# Packages #
############

packages:
  # Connection
  connection: !include common/connection.yaml
  # Extras
  extras: !include common/extras.yaml

###########
# Sensors #
###########

binary_sensor:
  - platform: gpio
    name: Socket Button
    pin:
      number: P24
      mode: INPUT_PULLUP
      inverted: true

    on_click:
      - switch.toggle: relay

##########
# Relays #
##########

switch:
  - platform: gpio
    pin: P6
    id: relay
    inverted: false
    name: Socket Relay
    icon: "mdi:power-socket-uk"
    on_turn_on:
      - output.turn_on: led_red
    on_turn_off:
      - output.turn_off: led_red

########
# LEDs #
########

output:
  - platform: gpio
    pin: P7
    inverted: false
    id: led_red

  - platform: gpio
    pin: P26
    inverted: false
    id: led_blue

################
# Power Sensor #
################

sensor:
  - platform: hlw8012
    model: bl0937

    sel_pin:
      number: P9
      inverted: true
    cf_pin:
      number: P20
      inverted: true
    cf1_pin:
      number: P8
      inverted: true

    voltage_divider: 781.0662292623375
    current_resistor: 0.000989624094895091

    update_interval: 5s

    current:
      name: "Current"
      filters:
        - multiply: 0.4402206705237544
      on_value_range:
        - above: ${current_limit}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: notify.notify
                data:
                  message: "High Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"
    energy:
      name: "Energy"

  # Internal Temperature
  - platform: internal_temperature
    name: Internal Temperature
    update_interval: ${sensors_update}
    on_value_range:
      - above: ${temperature_limit}
        then:
          - switch.turn_off: relay
          - homeassistant.service:
              service: notify.notify
              data:
                message: "Internal Temperature"