#################
# Substitutions #
#################

substitutions:
  delay: 135ms

##################
# Sender Remotes #
##################

script:

# ### Soundbar ### #

  - id: soundbar_power
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8001
  - id: soundbar_input
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8002
  - id: soundbar_mute
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8033
  - id: soundbar_volume_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8003
  - id: soundbar_volume_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8008
  - id: soundbar_bass_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8004
  - id: soundbar_bass_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8026
  - id: soundbar_trebble_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8025
  - id: soundbar_trebble_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8027

# ### HDMI Switch ### #

  - id: hdmi_switch_power_on
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x805C
  - id: hdmi_switch_power_off
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801F
  - id: hdmi_switch_device_1
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801B
  - id: hdmi_switch_device_2
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x801E
  - id: hdmi_switch_device_3
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800D
  - id: hdmi_switch_device_4
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8012
  - id: hdmi_switch_device_5
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8010
  - id: hdmi_switch_device_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x800C
  - id: hdmi_switch_device_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x8005

# ### Roku ### #

  - id: roku_home
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743C13E
          nbits: 32
  - id: roku_back
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57436798
          nbits: 32
  - id: roku_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57439966
          nbits: 32
  - id: roku_left
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57437986
          nbits: 32
  - id: roku_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743CD32
          nbits: 32
  - id: roku_right
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743B54A
          nbits: 32
  - id: roku_select
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x574355AA
          nbits: 32
  - id: roku_replay
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57431FE0
          nbits: 32
  - id: roku_options
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57438778
          nbits: 32
  - id: roku_previous
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x57432DD2
          nbits: 32
  - id: roku_next
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x5743AB54
          nbits: 32
  - id: roku_play_pause
    then:
      - delay: $delay
      - remote_transmitter.transmit_lg:
          transmitter_id: transmitter_ir
          data: 0x574333CC
          nbits: 32

# ### Samsung TV ### #

  - id: samsung_power
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E06798
          nbits: 32

  - id: samsung_source
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0807F
          nbits: 32

  - id: samsung_mute
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0F00F
          nbits: 32

  - id: samsung_volume_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0E01F
          nbits: 32

  - id: samsung_volume_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0D02F
          nbits: 32

  - id: samsung_channel_list
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0D629
          nbits: 32

  - id: samsung_channel_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E048B7
          nbits: 32

  - id: samsung_channel_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E008F7
          nbits: 32

  - id: samsung_home
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E09E61
          nbits: 32

  - id: samsung_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E006F9
          nbits: 32

  - id: samsung_left
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0A659
          nbits: 32

  - id: samsung_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E08679
          nbits: 32

  - id: samsung_right
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E046B9
          nbits: 32

  - id: samsung_select
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E016E9
          nbits: 32

  - id: samsung_return
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E01AE5
          nbits: 32

  - id: samsung_exit
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E0B44B
          nbits: 32

  - id: samsung_settings
    then:
      - delay: $delay
      - remote_transmitter.transmit_samsung:
          transmitter_id: transmitter_ir
          data: 0xE0E058A7
          nbits: 32

# ### Wimius Projector ### #

  - id: projector_power
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x100B

  - id: projector_source
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x100C

  - id: projector_home
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x101A

  - id: projector_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1050

  - id: projector_left
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1051

  - id: projector_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1053

  - id: projector_right
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1052

  - id: projector_select
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x101C

  - id: projector_options
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1017

  - id: projector_back
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1015

  - id: projector_auto_focus
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x10B6

  - id: projector_mute
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1014

  - id: projector_volume_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1048

  - id: projector_volume_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1049

  - id: projector_focus_up
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1056

  - id: projector_focus_down
    then:
      - delay: $delay
      - remote_transmitter.transmit_pioneer:
          transmitter_id: transmitter_ir
          rc_code_1: 0x1057

# ### Duronic Projector Screen ### #

  - id: screen_hide
    then:
      - remote_transmitter.transmit_raw:
          transmitter_id: transmitter_rf
          code: [
            # F3 BD CD 80
            # 1111001110111101110011011
            # Start
            192,
            # Space + Previous End
            -5896,
            # ### Code & Space x 4 ### #
            # First
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568,
            568, -192,
            192, -568, 192,
            # Space + Previous End
            -5896,
            # Second
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568,
            568, -192,
            192, -568, 192,
            # Space + Previous End
            -5896,
            # Third
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568,
            568, -192,
            192, -568, 192,
            # Space + Previous End
            -5896,
            # Fourth
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568,
            568, -192,
            192, -568, 192,
            # Space + Previous End
            -5896
          ]

  - id: screen_stop
    then:
      - remote_transmitter.transmit_raw:
          transmitter_id: transmitter_rf
          code: [
            # F3 BD C7 80
            # 1111001110111101110001111
            # Start
            192,
            # Space + Previous End
            -5896,
            # ### Code & Space x 4 ### #
            # First
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192, 568, -192,
            192, -568, 192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Second
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192, 568, -192,
            192, -568, 192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Third
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192, 568, -192,
            192, -568, 192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Fourth
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192, 568, -192,
            192, -568, 192, -568, 192, -568, 192,
            # Space + Previous End
            -5896
          ]

  - id: screen_show
    then:
      - remote_transmitter.transmit_raw:
          transmitter_id: transmitter_rf
          code: [
            # F3 BD CB 80
            # 1111001110111101110010111
            # Start
            192,
            # Space + Previous End
            -5896,
            # ### Code & Space x 4 ### #
            # First
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568,
            568, -192,
            192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Second
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568,
            568, -192,
            192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Third
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568,
            568, -192,
            192, -568, 192, -568, 192,
            # Space + Previous End
            -5896,
            # Fourth
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568, 192, -568,
            568, -192,
            192, -568, 192, -568, 192, -568,
            568, -192, 568, -192,
            192, -568,
            568, -192,
            192, -568, 192, -568, 192,
            # Space + Previous End
            -5896
          ]
